Kslhacks/tab component
great-lakes/project-superior-dashboard pull request #14
Opened 2018-01-30 23:16 UTC by KSLHacks

TabMenu component implemented with redux and routing.

Closes #8, #11, #12

2018-01-31 17:21 UTC, howlowck requested changes
* See comments

2018-01-31 17:21 UTC, howlowck commented on src/components/App/index.js
> +import App from './App.js'
You don't need `.js` extension here

2018-01-31 17:32 UTC, KSLHacks commented on src/components/App/index.js
> +import App from './App.js'
Removed .js extension on import. 👍

2018-02-02 18:12 UTC, howlowck approved these changes

2018-02-02 18:17 UTC, merged